trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

stages:
  - stage: Build Stage
    displayName: Build Stage
    jobs:
    - job: BuildNuget
      displayName: Build NuGet Packages
      variables:
        BuildConfiguration: release
      steps:
      #### Install dependencies 
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
            feedsToUse: select

        ### build and generate dll's
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(BuildConfiguration)'
        
        ### Generate new nuget package
        - task: DotNetCoreCLI@2
          inputs:
            command: 'pack'
            packagesToPack: '**/*.csproj'
            versioningScheme: 'off'

        #### Push NuGet package to ADO Artifacts
        - task: DotNetCoreCLI@2
          inputs:
            command: 'push'
            packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
            nuGetFeedType: 'internal'
            publishVstsFeed: 'e37bb405-f271-428f-b3a7-fbd365f467ad/a5cd986e-d9db-459f-a009-02f43a62507c'